steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/iroiro-175105/my-api:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/iroiro-175105/my-api:$TAG_NAME']
- name: 'gcr.io/iroiro-175105/deploy:v1'
  args: ['$TAG_NAME']