steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/iroiro-175105/my-api:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/iroiro-175105/my-api:$TAG_NAME']
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: ./deploy.sh
  args: ['$TAG_NAME']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'